server:
  port: 8886
  tomcat:
      uri-encoding: utf-8
  # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
  max-http-header-size: 8192
  use-forward-headers: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    # 配置thymeleaf修改页面不重启生效
    cache: false
    encoding: utf-8
    mode: LEGACYHTML5
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hope?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      filters: stat,wall,slf4j
  # Redis
  redis:
      database: 12
      host: localhost
      port: 6379
      #密码默认为空，注释即可，要添加密码，去掉注释添加就行
      #password:
      pool: #star
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0 #end
      # 连接超时时间（毫秒）
      timeout:  3000
      # 默认的数据过期时间，主要用于shiro权限管理
      expire: 2592000
  profiles:
    active: dev
  application:
      name: hope-admin
mybatis:
    type-aliases-package: com.hope.model.beans
    mapper-locations: classpath:/mybatis/*.xml
mapper:
    mappers:
        - com.hope.mybatis.mapper.BaseMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql
logging:
    file: ./logs/log.log
    level:
      com.hope: DEBUG
      tk.mybatis: DEBUG
      org.springframework: WARN
################################### hope-boot自定义配置 ###################################
hope:
    druid:
        # druid访问用户名（默认：hope-druid）
        username: hope-druid
        # druid访问密码（默认：hope-druid）
        password: hope-druid
        # druid访问地址（默认：/druid/*）
        servletPath: /druid/*
        # 启用重置功能（默认false）
        resetEnable: false
        # 白名单(非必填)， list
        allowIps[0]:
        # 黑名单(非必填)， list
        denyIps[0]:
#swagger入口： http://localhost:8886/swagger-ui.html#/
